### ISSUE TITLE
生成规则列表包含非公网 IP

### ISSUE THREAD

**Issue by SeaHOH** [PBH-BTN/Sparkle#2]
https://github.com/PBH-BTN/BTN-Collected-Rules/issues/19

**Comment by catscarlet** [comment]
![screenshot_on_b85m_by_flameshot_at_2024-10-06_15-49-56](https://github.com/user-attachments/assets/8ff539fc-7a34-4ab9-b810-45a582955313)

**Comment by Ghost-chu** [comment]
目前暂时在报告到 github 之前过滤掉了，但核心部分还没过滤。晚点治本。

**Comment by Ghost-chu** [comment]
现在会在生成规则时过滤此类 IP

close PBH-BTN/BTN-Collected-Rules#19

**Comment by SeaHOH** [comment]
不应该使用`IPAddress::isAnyLocal`判断，这个等效`IPAddress::isZero`，应使用`IPAddress::isLocal`。

**Comment by SeaHOH** [comment]
有点奇怪，还有`192.168.2.253`混在`random_peerid.txt`里面。
