### ISSUE TITLE
Snapshot 的 PeerIp 的错误实现

### ISSUE THREAD

**Issue by cxzlw** [PBH-BTN/Sparkle#4]
https://github.com/PBH-BTN/Sparkle/blob/99762f95f8613c070ed858ddcba1012609579faa/src/main/java/com/ghostchu/btn/sparkle/module/snapshot/SnapshotService.java#L83

这行把 `PeerId` 放到 `PeerIp` 里面了……

**Comment by Ghost-chu** [comment]
fixed
